### ISSUE TITLE
Evidence attribute structure in EBSI schemas

### ISSUE THREAD

**Issue by albertoabellagarcia** [alastria/alastria-identity-schemas#15]
Aquí podéis ver los ejemplos en los que me base para la extensión del atributo evidence

- https://ec.europa.eu/digital-building-blocks/code/projects/EBSI/repos/json-schema/browse/schemas/ebsi-muti-uni-pilot/verifiable-attestation-organisational-id/2022-11/examples/Bengales_organizationVerifiableAttestation.json#25,27,30
- https://ec.europa.eu/digital-building-blocks/code/projects/EBSI/repos/json-schema/browse/schemas/ebsi-muti-uni-pilot/verifiable-attestation-individual-id/2022-11/examples/Bengales_individualVerifiableAttestation.json#36,38,41
- https://ec.europa.eu/digital-building-blocks/code/projects/EBSI/repos/json-schema/browse/schemas/ebsi-muti-uni-pilot/verifiable-attestation-individual-id/2022-11/examples/individualVerifiableAttestation_MyAcademicIDexample.json#31,33,36

Con lo que para que se validen los ejemplos tuve que ampliar el schema

**Comment by alejandro-nieto-git** [comment]
Perfecto, incorporo esos campos de la Verifiable Attestation de Smart Data Models al schema que tenemos en el repositorio de schemas de AlastriaID. Lo único que voy a mantener el @context como campo obligatorio, que así se establece en la documentación de EBSI.
